import Header from './components/Header/Header';
import './globals.css';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['cyrillic', 'latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-base dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200 min-h-screen ${roboto.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
